<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!DOCTYPE spamo[
<!ELEMENT spamo (model, files, primary_motif, run_time)>
<!ATTLIST spamo version CDATA #REQUIRED release CDATA #REQUIRED>
<!ELEMENT model (command_line, seed, margin, bin_size,
  bin_pvalue_calc_range, bin_pvalue_cutoff, seq_max_shared_fract,
  seq_min_hit_score, redundant_overlap, redundant_joint,
  motif_pseudocount, motif_trim, bin_max, host, when)>
<!ELEMENT command_line (#PCDATA)>
<!ELEMENT seed (#PCDATA)>
<!ELEMENT margin (#PCDATA)>
<!ELEMENT bin_size (#PCDATA)>
<!ELEMENT bin_pvalue_calc_range (#PCDATA)>
<!ELEMENT bin_pvalue_cutoff (#PCDATA)>
<!ELEMENT seq_max_shared_fract (#PCDATA)>
<!ELEMENT seq_min_hit_score (#PCDATA)>
<!ELEMENT redundant_overlap (#PCDATA)>
<!ELEMENT redundant_joint (#PCDATA)>
<!ELEMENT motif_pseudocount (#PCDATA)>
<!ELEMENT motif_trim (#PCDATA)>
<!ELEMENT bin_max (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT when (#PCDATA)>
<!ELEMENT files (sequence_db, motif_db*)>
<!ELEMENT sequence_db EMPTY>
<!ATTLIST sequence_db name CDATA #REQUIRED loaded CDATA #REQUIRED
  excluded_too_short CDATA #REQUIRED excluded_no_match CDATA #REQUIRED
  excluded_similar CDATA #REQUIRED last_modified CDATA #REQUIRED
  source CDATA #REQUIRED>
<!ELEMENT motif_db EMPTY>
<!ATTLIST motif_db id ID #REQUIRED name CDATA #REQUIRED
  loaded CDATA #REQUIRED excluded CDATA #REQUIRED
  last_modified CDATA #REQUIRED source CDATA #REQUIRED
  cisml CDATA #IMPLIED>
<!ELEMENT primary_motif (motif, secondary_motif*)>
<!ELEMENT secondary_motif (spacing*, motif, histogram, redundant?)>
<!ATTLIST secondary_motif evalue CDATA #REQUIRED>
<!ELEMENT spacing EMPTY>
<!ATTLIST spacing strand (same|opposite) #REQUIRED
  side (left|right) #REQUIRED bin CDATA #REQUIRED num CDATA #REQUIRED
  pvalue CDATA #REQUIRED>
<!ELEMENT histogram (same_strand, opposite_strand)>
<!ATTLIST histogram total CDATA #REQUIRED max CDATA #REQUIRED>
<!ELEMENT same_strand (left_side, right_side)>
<!ELEMENT opposite_strand (left_side, right_side)>
<!ELEMENT left_side (bin*)>
<!ELEMENT right_side (bin*)>
<!ELEMENT bin EMPTY>
<!-- i: index, n: number in bin, p: pvalue (only supplied when bin
  is tested) -->
<!ATTLIST bin i CDATA #REQUIRED n CDATA #REQUIRED p CDATA #IMPLIED>
<!ELEMENT redundant (secondary_motif*)>
<!-- motif contains the probability of each of the nucleotide bases at each
  position; i starts at 1; A, C, G and T are probabilities that sum to 1 -->
<!ELEMENT motif (pos*)>
<!ATTLIST motif db IDREF #REQUIRED name CDATA #REQUIRED alt CDATA #IMPLIED 
  length CDATA #REQUIRED nsites CDATA #IMPLIED evalue CDATA #IMPLIED
  ltrim CDATA #IMPLIED rtrim CDATA #IMPLIED url CDATA #IMPLIED>
<!ELEMENT pos EMPTY>
<!ATTLIST pos i CDATA #REQUIRED A CDATA #REQUIRED C CDATA #REQUIRED
  G CDATA #REQUIRED T CDATA #REQUIRED>
<!-- run time is measured in real time and cpu time -->
<!ELEMENT run_time EMPTY>
<!ATTLIST run_time cpu CDATA #REQUIRED real CDATA #REQUIRED>
]>
<spamo version="4.10.0" release="Wed May 21 10:35:36 2014 +1000">
  <model>
    <command_line>spamo  -verbosity 1 -oc ERR649812_cnc_memeChip/spamo_out_1 -bgfile ERR649812_cnc_memeChip/background -primary 1 ERR649812_cnc_memeChip/ERR649812_cnc.fasta ERR649812_cnc_memeChip/meme_out/meme.xml ERR649812_cnc_memeChip/meme_out/meme.xml</command_line>
    <seed>1</seed>
    <margin>150</margin>
    <bin_size>1</bin_size>
    <bin_pvalue_calc_range>150</bin_pvalue_calc_range>
    <bin_pvalue_cutoff>0.05</bin_pvalue_cutoff>
    <motif_evalue_cutoff>10</motif_evalue_cutoff>
    <seq_max_shared_fract>0.5</seq_max_shared_fract>
    <seq_min_hit_score>7</seq_min_hit_score>
    <redundant_overlap>2</redundant_overlap>
    <redundant_joint>0.5</redundant_joint>
    <motif_pseudocount>0.1</motif_pseudocount>
    <motif_trim>0.25</motif_trim>
    <bin_max>0</bin_max>
    <host>thymine.cgrb.oregonstate.local</host>
    <when>Tue Apr  2 14:21:54 2019</when>
  </model>
  <files>
    <sequence_db name="ERR649812 cnc" loaded="49830" excluded_too_short="49830"
        excluded_no_match="0" excluded_similar="0" last_modified="Tue Apr  2 13:33:42 2019"
        source="ERR649812_cnc_memeChip/ERR649812_cnc.fasta"/>
    <motif_db id="primary_file" name="meme.xml" loaded="2" excluded="1" last_modified="Tue Apr  2 14:21:50 2019"
        source="ERR649812_cnc_memeChip/meme_out/meme.xml"/>
    <motif_db id="db1" name="meme.xml" loaded="3" excluded="1" last_modified="Tue Apr  2 14:21:50 2019"
        source="ERR649812_cnc_memeChip/meme_out/meme.xml"/>
  </files>
  <primary_motif>
    <motif db="primary_file" name="1" alt="MEME" length="11" nsites="22" evalue="64" ltrim="0" rtrim="0" >
      <pos i="1" A="0.0916406" C="0.679852" G="0.0463688" T="0.182138"/>
      <pos i="2" A="0.634628" C="0.36311" G="0.00111946" T="0.00114299"/>
      <pos i="3" A="0.272636" C="0.36311" G="0.36311" T="0.00114299"/>
      <pos i="4" A="0.54413" C="0.408359" G="0.0463688" T="0.00114299"/>
      <pos i="5" A="0.408383" C="0.272612" G="0.317862" T="0.00114299"/>
      <pos i="6" A="0.00114299" C="0.00111946" G="0.00111946" T="0.996618"/>
      <pos i="7" A="0.00114299" C="0.00111946" G="0.996595" T="0.00114299"/>
      <pos i="8" A="0.996618" C="0.00111946" G="0.00111946" T="0.00114299"/>
      <pos i="9" A="0.00114299" C="0.996595" G="0.00111946" T="0.00114299"/>
      <pos i="10" A="0.90612" C="0.00111946" G="0.0916171" T="0.00114299"/>
      <pos i="11" A="0.00114299" C="0.544106" G="0.136866" T="0.317885"/>
    </motif>
    <secondary_motif evalue="2">
            <motif db="db1" name="2" alt="MEME" length="20" nsites="13" evalue="1800" ltrim="0" rtrim="0" >
        <pos i="1" A="0.1546" C="0.00188855" G="0.688912" T="0.1546"/>
        <pos i="2" A="0.00192824" C="0.841583" G="0.0782244" T="0.078264"/>
        <pos i="3" A="0.765287" C="0.00188855" G="0.15456" T="0.078264"/>
        <pos i="4" A="0.00192824" C="0.230896" G="0.15456" T="0.612616"/>
        <pos i="5" A="0.307271" C="0.00188855" G="0.688912" T="0.00192824"/>
        <pos i="6" A="0.00192824" C="0.917919" G="0.00188855" T="0.078264"/>
        <pos i="7" A="0.230936" C="0.765248" G="0.00188855" T="0.00192824"/>
        <pos i="8" A="0.1546" C="0.15456" G="0.459903" T="0.230936"/>
        <pos i="9" A="0.1546" C="0.53624" G="0.00188855" T="0.307271"/>
        <pos i="10" A="0.00192824" C="0.612576" G="0.383568" T="0.00192824"/>
        <pos i="11" A="0.1546" C="0.459903" G="0.0782244" T="0.307271"/>
        <pos i="12" A="0.612616" C="0.0782244" G="0.307232" T="0.00192824"/>
        <pos i="13" A="0.230936" C="0.0782244" G="0.00188855" T="0.688951"/>
        <pos i="14" A="0.307271" C="0.307232" G="0.307232" T="0.078264"/>
        <pos i="15" A="0.1546" C="0.688912" G="0.15456" T="0.00192824"/>
        <pos i="16" A="0.765287" C="0.15456" G="0.0782244" T="0.00192824"/>
        <pos i="17" A="0.307271" C="0.53624" G="0.0782244" T="0.078264"/>
        <pos i="18" A="0.307271" C="0.307232" G="0.383568" T="0.00192824"/>
        <pos i="19" A="0.00192824" C="0.459903" G="0.53624" T="0.00192824"/>
        <pos i="20" A="0.307271" C="0.53624" G="0.0782244" T="0.078264"/>
      </motif>
      <histogram total="0" max="0">
        <same_strand>
          <left_side>
            <bin i="1" n="0"/>
            <bin i="2" n="0"/>
            <bin i="3" n="0"/>
            <bin i="4" n="0"/>
            <bin i="5" n="0"/>
            <bin i="6" n="0"/>
            <bin i="7" n="0"/>
            <bin i="8" n="0"/>
            <bin i="9" n="0"/>
            <bin i="10" n="0"/>
            <bin i="11" n="0"/>
            <bin i="12" n="0"/>
            <bin i="13" n="0"/>
            <bin i="14" n="0"/>
            <bin i="15" n="0"/>
            <bin i="16" n="0"/>
            <bin i="17" n="0"/>
            <bin i="18" n="0"/>
            <bin i="19" n="0"/>
            <bin i="20" n="0"/>
            <bin i="21" n="0"/>
            <bin i="22" n="0"/>
            <bin i="23" n="0"/>
            <bin i="24" n="0"/>
            <bin i="25" n="0"/>
            <bin i="26" n="0"/>
            <bin i="27" n="0"/>
            <bin i="28" n="0"/>
            <bin i="29" n="0"/>
            <bin i="30" n="0"/>
            <bin i="31" n="0"/>
            <bin i="32" n="0"/>
            <bin i="33" n="0"/>
            <bin i="34" n="0"/>
            <bin i="35" n="0"/>
            <bin i="36" n="0"/>
            <bin i="37" n="0"/>
            <bin i="38" n="0"/>
            <bin i="39" n="0"/>
            <bin i="40" n="0"/>
            <bin i="41" n="0"/>
            <bin i="42" n="0"/>
            <bin i="43" n="0"/>
            <bin i="44" n="0"/>
            <bin i="45" n="0"/>
            <bin i="46" n="0"/>
            <bin i="47" n="0"/>
            <bin i="48" n="0"/>
            <bin i="49" n="0"/>
            <bin i="50" n="0"/>
            <bin i="51" n="0"/>
            <bin i="52" n="0"/>
            <bin i="53" n="0"/>
            <bin i="54" n="0"/>
            <bin i="55" n="0"/>
            <bin i="56" n="0"/>
            <bin i="57" n="0"/>
            <bin i="58" n="0"/>
            <bin i="59" n="0"/>
            <bin i="60" n="0"/>
            <bin i="61" n="0"/>
            <bin i="62" n="0"/>
            <bin i="63" n="0"/>
            <bin i="64" n="0"/>
            <bin i="65" n="0"/>
            <bin i="66" n="0"/>
            <bin i="67" n="0"/>
            <bin i="68" n="0"/>
            <bin i="69" n="0"/>
            <bin i="70" n="0"/>
            <bin i="71" n="0"/>
            <bin i="72" n="0"/>
            <bin i="73" n="0"/>
            <bin i="74" n="0"/>
            <bin i="75" n="0"/>
            <bin i="76" n="0"/>
            <bin i="77" n="0"/>
            <bin i="78" n="0"/>
            <bin i="79" n="0"/>
            <bin i="80" n="0"/>
            <bin i="81" n="0"/>
            <bin i="82" n="0"/>
            <bin i="83" n="0"/>
            <bin i="84" n="0"/>
            <bin i="85" n="0"/>
            <bin i="86" n="0"/>
            <bin i="87" n="0"/>
            <bin i="88" n="0"/>
            <bin i="89" n="0"/>
            <bin i="90" n="0"/>
            <bin i="91" n="0"/>
            <bin i="92" n="0"/>
            <bin i="93" n="0"/>
            <bin i="94" n="0"/>
            <bin i="95" n="0"/>
            <bin i="96" n="0"/>
            <bin i="97" n="0"/>
            <bin i="98" n="0"/>
            <bin i="99" n="0"/>
            <bin i="100" n="0"/>
            <bin i="101" n="0"/>
            <bin i="102" n="0"/>
            <bin i="103" n="0"/>
            <bin i="104" n="0"/>
            <bin i="105" n="0"/>
            <bin i="106" n="0"/>
            <bin i="107" n="0"/>
            <bin i="108" n="0"/>
            <bin i="109" n="0"/>
            <bin i="110" n="0"/>
            <bin i="111" n="0"/>
            <bin i="112" n="0"/>
            <bin i="113" n="0"/>
            <bin i="114" n="0"/>
            <bin i="115" n="0"/>
            <bin i="116" n="0"/>
            <bin i="117" n="0"/>
            <bin i="118" n="0"/>
            <bin i="119" n="0"/>
            <bin i="120" n="0"/>
            <bin i="121" n="0"/>
            <bin i="122" n="0"/>
            <bin i="123" n="0"/>
            <bin i="124" n="0"/>
            <bin i="125" n="0"/>
            <bin i="126" n="0"/>
            <bin i="127" n="0"/>
            <bin i="128" n="0"/>
            <bin i="129" n="0"/>
            <bin i="130" n="0"/>
            <bin i="131" n="0"/>
          </left_side>
          <right_side>
            <bin i="1" n="0"/>
            <bin i="2" n="0"/>
            <bin i="3" n="0"/>
            <bin i="4" n="0"/>
            <bin i="5" n="0"/>
            <bin i="6" n="0"/>
            <bin i="7" n="0"/>
            <bin i="8" n="0"/>
            <bin i="9" n="0"/>
            <bin i="10" n="0"/>
            <bin i="11" n="0"/>
            <bin i="12" n="0"/>
            <bin i="13" n="0"/>
            <bin i="14" n="0"/>
            <bin i="15" n="0"/>
            <bin i="16" n="0"/>
            <bin i="17" n="0"/>
            <bin i="18" n="0"/>
            <bin i="19" n="0"/>
            <bin i="20" n="0"/>
            <bin i="21" n="0"/>
            <bin i="22" n="0"/>
            <bin i="23" n="0"/>
            <bin i="24" n="0"/>
            <bin i="25" n="0"/>
            <bin i="26" n="0"/>
            <bin i="27" n="0"/>
            <bin i="28" n="0"/>
            <bin i="29" n="0"/>
            <bin i="30" n="0"/>
            <bin i="31" n="0"/>
            <bin i="32" n="0"/>
            <bin i="33" n="0"/>
            <bin i="34" n="0"/>
            <bin i="35" n="0"/>
            <bin i="36" n="0"/>
            <bin i="37" n="0"/>
            <bin i="38" n="0"/>
            <bin i="39" n="0"/>
            <bin i="40" n="0"/>
            <bin i="41" n="0"/>
            <bin i="42" n="0"/>
            <bin i="43" n="0"/>
            <bin i="44" n="0"/>
            <bin i="45" n="0"/>
            <bin i="46" n="0"/>
            <bin i="47" n="0"/>
            <bin i="48" n="0"/>
            <bin i="49" n="0"/>
            <bin i="50" n="0"/>
            <bin i="51" n="0"/>
            <bin i="52" n="0"/>
            <bin i="53" n="0"/>
            <bin i="54" n="0"/>
            <bin i="55" n="0"/>
            <bin i="56" n="0"/>
            <bin i="57" n="0"/>
            <bin i="58" n="0"/>
            <bin i="59" n="0"/>
            <bin i="60" n="0"/>
            <bin i="61" n="0"/>
            <bin i="62" n="0"/>
            <bin i="63" n="0"/>
            <bin i="64" n="0"/>
            <bin i="65" n="0"/>
            <bin i="66" n="0"/>
            <bin i="67" n="0"/>
            <bin i="68" n="0"/>
            <bin i="69" n="0"/>
            <bin i="70" n="0"/>
            <bin i="71" n="0"/>
            <bin i="72" n="0"/>
            <bin i="73" n="0"/>
            <bin i="74" n="0"/>
            <bin i="75" n="0"/>
            <bin i="76" n="0"/>
            <bin i="77" n="0"/>
            <bin i="78" n="0"/>
            <bin i="79" n="0"/>
            <bin i="80" n="0"/>
            <bin i="81" n="0"/>
            <bin i="82" n="0"/>
            <bin i="83" n="0"/>
            <bin i="84" n="0"/>
            <bin i="85" n="0"/>
            <bin i="86" n="0"/>
            <bin i="87" n="0"/>
            <bin i="88" n="0"/>
            <bin i="89" n="0"/>
            <bin i="90" n="0"/>
            <bin i="91" n="0"/>
            <bin i="92" n="0"/>
            <bin i="93" n="0"/>
            <bin i="94" n="0"/>
            <bin i="95" n="0"/>
            <bin i="96" n="0"/>
            <bin i="97" n="0"/>
            <bin i="98" n="0"/>
            <bin i="99" n="0"/>
            <bin i="100" n="0"/>
            <bin i="101" n="0"/>
            <bin i="102" n="0"/>
            <bin i="103" n="0"/>
            <bin i="104" n="0"/>
            <bin i="105" n="0"/>
            <bin i="106" n="0"/>
            <bin i="107" n="0"/>
            <bin i="108" n="0"/>
            <bin i="109" n="0"/>
            <bin i="110" n="0"/>
            <bin i="111" n="0"/>
            <bin i="112" n="0"/>
            <bin i="113" n="0"/>
            <bin i="114" n="0"/>
            <bin i="115" n="0"/>
            <bin i="116" n="0"/>
            <bin i="117" n="0"/>
            <bin i="118" n="0"/>
            <bin i="119" n="0"/>
            <bin i="120" n="0"/>
            <bin i="121" n="0"/>
            <bin i="122" n="0"/>
            <bin i="123" n="0"/>
            <bin i="124" n="0"/>
            <bin i="125" n="0"/>
            <bin i="126" n="0"/>
            <bin i="127" n="0"/>
            <bin i="128" n="0"/>
            <bin i="129" n="0"/>
            <bin i="130" n="0"/>
            <bin i="131" n="0"/>
          </right_side>
        </same_strand>
        <opposite_strand>
          <left_side>
            <bin i="1" n="0"/>
            <bin i="2" n="0"/>
            <bin i="3" n="0"/>
            <bin i="4" n="0"/>
            <bin i="5" n="0"/>
            <bin i="6" n="0"/>
            <bin i="7" n="0"/>
            <bin i="8" n="0"/>
            <bin i="9" n="0"/>
            <bin i="10" n="0"/>
            <bin i="11" n="0"/>
            <bin i="12" n="0"/>
            <bin i="13" n="0"/>
            <bin i="14" n="0"/>
            <bin i="15" n="0"/>
            <bin i="16" n="0"/>
            <bin i="17" n="0"/>
            <bin i="18" n="0"/>
            <bin i="19" n="0"/>
            <bin i="20" n="0"/>
            <bin i="21" n="0"/>
            <bin i="22" n="0"/>
            <bin i="23" n="0"/>
            <bin i="24" n="0"/>
            <bin i="25" n="0"/>
            <bin i="26" n="0"/>
            <bin i="27" n="0"/>
            <bin i="28" n="0"/>
            <bin i="29" n="0"/>
            <bin i="30" n="0"/>
            <bin i="31" n="0"/>
            <bin i="32" n="0"/>
            <bin i="33" n="0"/>
            <bin i="34" n="0"/>
            <bin i="35" n="0"/>
            <bin i="36" n="0"/>
            <bin i="37" n="0"/>
            <bin i="38" n="0"/>
            <bin i="39" n="0"/>
            <bin i="40" n="0"/>
            <bin i="41" n="0"/>
            <bin i="42" n="0"/>
            <bin i="43" n="0"/>
            <bin i="44" n="0"/>
            <bin i="45" n="0"/>
            <bin i="46" n="0"/>
            <bin i="47" n="0"/>
            <bin i="48" n="0"/>
            <bin i="49" n="0"/>
            <bin i="50" n="0"/>
            <bin i="51" n="0"/>
            <bin i="52" n="0"/>
            <bin i="53" n="0"/>
            <bin i="54" n="0"/>
            <bin i="55" n="0"/>
            <bin i="56" n="0"/>
            <bin i="57" n="0"/>
            <bin i="58" n="0"/>
            <bin i="59" n="0"/>
            <bin i="60" n="0"/>
            <bin i="61" n="0"/>
            <bin i="62" n="0"/>
            <bin i="63" n="0"/>
            <bin i="64" n="0"/>
            <bin i="65" n="0"/>
            <bin i="66" n="0"/>
            <bin i="67" n="0"/>
            <bin i="68" n="0"/>
            <bin i="69" n="0"/>
            <bin i="70" n="0"/>
            <bin i="71" n="0"/>
            <bin i="72" n="0"/>
            <bin i="73" n="0"/>
            <bin i="74" n="0"/>
            <bin i="75" n="0"/>
            <bin i="76" n="0"/>
            <bin i="77" n="0"/>
            <bin i="78" n="0"/>
            <bin i="79" n="0"/>
            <bin i="80" n="0"/>
            <bin i="81" n="0"/>
            <bin i="82" n="0"/>
            <bin i="83" n="0"/>
            <bin i="84" n="0"/>
            <bin i="85" n="0"/>
            <bin i="86" n="0"/>
            <bin i="87" n="0"/>
            <bin i="88" n="0"/>
            <bin i="89" n="0"/>
            <bin i="90" n="0"/>
            <bin i="91" n="0"/>
            <bin i="92" n="0"/>
            <bin i="93" n="0"/>
            <bin i="94" n="0"/>
            <bin i="95" n="0"/>
            <bin i="96" n="0"/>
            <bin i="97" n="0"/>
            <bin i="98" n="0"/>
            <bin i="99" n="0"/>
            <bin i="100" n="0"/>
            <bin i="101" n="0"/>
            <bin i="102" n="0"/>
            <bin i="103" n="0"/>
            <bin i="104" n="0"/>
            <bin i="105" n="0"/>
            <bin i="106" n="0"/>
            <bin i="107" n="0"/>
            <bin i="108" n="0"/>
            <bin i="109" n="0"/>
            <bin i="110" n="0"/>
            <bin i="111" n="0"/>
            <bin i="112" n="0"/>
            <bin i="113" n="0"/>
            <bin i="114" n="0"/>
            <bin i="115" n="0"/>
            <bin i="116" n="0"/>
            <bin i="117" n="0"/>
            <bin i="118" n="0"/>
            <bin i="119" n="0"/>
            <bin i="120" n="0"/>
            <bin i="121" n="0"/>
            <bin i="122" n="0"/>
            <bin i="123" n="0"/>
            <bin i="124" n="0"/>
            <bin i="125" n="0"/>
            <bin i="126" n="0"/>
            <bin i="127" n="0"/>
            <bin i="128" n="0"/>
            <bin i="129" n="0"/>
            <bin i="130" n="0"/>
            <bin i="131" n="0"/>
          </left_side>
          <right_side>
            <bin i="1" n="0"/>
            <bin i="2" n="0"/>
            <bin i="3" n="0"/>
            <bin i="4" n="0"/>
            <bin i="5" n="0"/>
            <bin i="6" n="0"/>
            <bin i="7" n="0"/>
            <bin i="8" n="0"/>
            <bin i="9" n="0"/>
            <bin i="10" n="0"/>
            <bin i="11" n="0"/>
            <bin i="12" n="0"/>
            <bin i="13" n="0"/>
            <bin i="14" n="0"/>
            <bin i="15" n="0"/>
            <bin i="16" n="0"/>
            <bin i="17" n="0"/>
            <bin i="18" n="0"/>
            <bin i="19" n="0"/>
            <bin i="20" n="0"/>
            <bin i="21" n="0"/>
            <bin i="22" n="0"/>
            <bin i="23" n="0"/>
            <bin i="24" n="0"/>
            <bin i="25" n="0"/>
            <bin i="26" n="0"/>
            <bin i="27" n="0"/>
            <bin i="28" n="0"/>
            <bin i="29" n="0"/>
            <bin i="30" n="0"/>
            <bin i="31" n="0"/>
            <bin i="32" n="0"/>
            <bin i="33" n="0"/>
            <bin i="34" n="0"/>
            <bin i="35" n="0"/>
            <bin i="36" n="0"/>
            <bin i="37" n="0"/>
            <bin i="38" n="0"/>
            <bin i="39" n="0"/>
            <bin i="40" n="0"/>
            <bin i="41" n="0"/>
            <bin i="42" n="0"/>
            <bin i="43" n="0"/>
            <bin i="44" n="0"/>
            <bin i="45" n="0"/>
            <bin i="46" n="0"/>
            <bin i="47" n="0"/>
            <bin i="48" n="0"/>
            <bin i="49" n="0"/>
            <bin i="50" n="0"/>
            <bin i="51" n="0"/>
            <bin i="52" n="0"/>
            <bin i="53" n="0"/>
            <bin i="54" n="0"/>
            <bin i="55" n="0"/>
            <bin i="56" n="0"/>
            <bin i="57" n="0"/>
            <bin i="58" n="0"/>
            <bin i="59" n="0"/>
            <bin i="60" n="0"/>
            <bin i="61" n="0"/>
            <bin i="62" n="0"/>
            <bin i="63" n="0"/>
            <bin i="64" n="0"/>
            <bin i="65" n="0"/>
            <bin i="66" n="0"/>
            <bin i="67" n="0"/>
            <bin i="68" n="0"/>
            <bin i="69" n="0"/>
            <bin i="70" n="0"/>
            <bin i="71" n="0"/>
            <bin i="72" n="0"/>
            <bin i="73" n="0"/>
            <bin i="74" n="0"/>
            <bin i="75" n="0"/>
            <bin i="76" n="0"/>
            <bin i="77" n="0"/>
            <bin i="78" n="0"/>
            <bin i="79" n="0"/>
            <bin i="80" n="0"/>
            <bin i="81" n="0"/>
            <bin i="82" n="0"/>
            <bin i="83" n="0"/>
            <bin i="84" n="0"/>
            <bin i="85" n="0"/>
            <bin i="86" n="0"/>
            <bin i="87" n="0"/>
            <bin i="88" n="0"/>
            <bin i="89" n="0"/>
            <bin i="90" n="0"/>
            <bin i="91" n="0"/>
            <bin i="92" n="0"/>
            <bin i="93" n="0"/>
            <bin i="94" n="0"/>
            <bin i="95" n="0"/>
            <bin i="96" n="0"/>
            <bin i="97" n="0"/>
            <bin i="98" n="0"/>
            <bin i="99" n="0"/>
            <bin i="100" n="0"/>
            <bin i="101" n="0"/>
            <bin i="102" n="0"/>
            <bin i="103" n="0"/>
            <bin i="104" n="0"/>
            <bin i="105" n="0"/>
            <bin i="106" n="0"/>
            <bin i="107" n="0"/>
            <bin i="108" n="0"/>
            <bin i="109" n="0"/>
            <bin i="110" n="0"/>
            <bin i="111" n="0"/>
            <bin i="112" n="0"/>
            <bin i="113" n="0"/>
            <bin i="114" n="0"/>
            <bin i="115" n="0"/>
            <bin i="116" n="0"/>
            <bin i="117" n="0"/>
            <bin i="118" n="0"/>
            <bin i="119" n="0"/>
            <bin i="120" n="0"/>
            <bin i="121" n="0"/>
            <bin i="122" n="0"/>
            <bin i="123" n="0"/>
            <bin i="124" n="0"/>
            <bin i="125" n="0"/>
            <bin i="126" n="0"/>
            <bin i="127" n="0"/>
            <bin i="128" n="0"/>
            <bin i="129" n="0"/>
            <bin i="130" n="0"/>
            <bin i="131" n="0"/>
          </right_side>
        </opposite_strand>
      </histogram>
    </secondary_motif>
    <secondary_motif evalue="2">
            <motif db="db1" name="3" alt="MEME" length="8" nsites="18" evalue="11000" ltrim="0" rtrim="0" >
        <pos i="1" A="0.995871" C="0.00136685" G="0.00136685" T="0.00139558"/>
        <pos i="2" A="0.00139558" C="0.995842" G="0.00136685" T="0.00139558"/>
        <pos i="3" A="0.995871" C="0.00136685" G="0.00136685" T="0.00139558"/>
        <pos i="4" A="0.00139558" C="0.553853" G="0.111864" T="0.332887"/>
        <pos i="5" A="0.167142" C="0.388107" G="0.443355" T="0.00139558"/>
        <pos i="6" A="0.00139558" C="0.00136685" G="0.00136685" T="0.995871"/>
        <pos i="7" A="0.00139558" C="0.00136685" G="0.00136685" T="0.995871"/>
        <pos i="8" A="0.00139558" C="0.00136685" G="0.995842" T="0.00139558"/>
      </motif>
      <histogram total="0" max="0">
        <same_strand>
          <left_side>
            <bin i="1" n="0"/>
            <bin i="2" n="0"/>
            <bin i="3" n="0"/>
            <bin i="4" n="0"/>
            <bin i="5" n="0"/>
            <bin i="6" n="0"/>
            <bin i="7" n="0"/>
            <bin i="8" n="0"/>
            <bin i="9" n="0"/>
            <bin i="10" n="0"/>
            <bin i="11" n="0"/>
            <bin i="12" n="0"/>
            <bin i="13" n="0"/>
            <bin i="14" n="0"/>
            <bin i="15" n="0"/>
            <bin i="16" n="0"/>
            <bin i="17" n="0"/>
            <bin i="18" n="0"/>
            <bin i="19" n="0"/>
            <bin i="20" n="0"/>
            <bin i="21" n="0"/>
            <bin i="22" n="0"/>
            <bin i="23" n="0"/>
            <bin i="24" n="0"/>
            <bin i="25" n="0"/>
            <bin i="26" n="0"/>
            <bin i="27" n="0"/>
            <bin i="28" n="0"/>
            <bin i="29" n="0"/>
            <bin i="30" n="0"/>
            <bin i="31" n="0"/>
            <bin i="32" n="0"/>
            <bin i="33" n="0"/>
            <bin i="34" n="0"/>
            <bin i="35" n="0"/>
            <bin i="36" n="0"/>
            <bin i="37" n="0"/>
            <bin i="38" n="0"/>
            <bin i="39" n="0"/>
            <bin i="40" n="0"/>
            <bin i="41" n="0"/>
            <bin i="42" n="0"/>
            <bin i="43" n="0"/>
            <bin i="44" n="0"/>
            <bin i="45" n="0"/>
            <bin i="46" n="0"/>
            <bin i="47" n="0"/>
            <bin i="48" n="0"/>
            <bin i="49" n="0"/>
            <bin i="50" n="0"/>
            <bin i="51" n="0"/>
            <bin i="52" n="0"/>
            <bin i="53" n="0"/>
            <bin i="54" n="0"/>
            <bin i="55" n="0"/>
            <bin i="56" n="0"/>
            <bin i="57" n="0"/>
            <bin i="58" n="0"/>
            <bin i="59" n="0"/>
            <bin i="60" n="0"/>
            <bin i="61" n="0"/>
            <bin i="62" n="0"/>
            <bin i="63" n="0"/>
            <bin i="64" n="0"/>
            <bin i="65" n="0"/>
            <bin i="66" n="0"/>
            <bin i="67" n="0"/>
            <bin i="68" n="0"/>
            <bin i="69" n="0"/>
            <bin i="70" n="0"/>
            <bin i="71" n="0"/>
            <bin i="72" n="0"/>
            <bin i="73" n="0"/>
            <bin i="74" n="0"/>
            <bin i="75" n="0"/>
            <bin i="76" n="0"/>
            <bin i="77" n="0"/>
            <bin i="78" n="0"/>
            <bin i="79" n="0"/>
            <bin i="80" n="0"/>
            <bin i="81" n="0"/>
            <bin i="82" n="0"/>
            <bin i="83" n="0"/>
            <bin i="84" n="0"/>
            <bin i="85" n="0"/>
            <bin i="86" n="0"/>
            <bin i="87" n="0"/>
            <bin i="88" n="0"/>
            <bin i="89" n="0"/>
            <bin i="90" n="0"/>
            <bin i="91" n="0"/>
            <bin i="92" n="0"/>
            <bin i="93" n="0"/>
            <bin i="94" n="0"/>
            <bin i="95" n="0"/>
            <bin i="96" n="0"/>
            <bin i="97" n="0"/>
            <bin i="98" n="0"/>
            <bin i="99" n="0"/>
            <bin i="100" n="0"/>
            <bin i="101" n="0"/>
            <bin i="102" n="0"/>
            <bin i="103" n="0"/>
            <bin i="104" n="0"/>
            <bin i="105" n="0"/>
            <bin i="106" n="0"/>
            <bin i="107" n="0"/>
            <bin i="108" n="0"/>
            <bin i="109" n="0"/>
            <bin i="110" n="0"/>
            <bin i="111" n="0"/>
            <bin i="112" n="0"/>
            <bin i="113" n="0"/>
            <bin i="114" n="0"/>
            <bin i="115" n="0"/>
            <bin i="116" n="0"/>
            <bin i="117" n="0"/>
            <bin i="118" n="0"/>
            <bin i="119" n="0"/>
            <bin i="120" n="0"/>
            <bin i="121" n="0"/>
            <bin i="122" n="0"/>
            <bin i="123" n="0"/>
            <bin i="124" n="0"/>
            <bin i="125" n="0"/>
            <bin i="126" n="0"/>
            <bin i="127" n="0"/>
            <bin i="128" n="0"/>
            <bin i="129" n="0"/>
            <bin i="130" n="0"/>
            <bin i="131" n="0"/>
            <bin i="132" n="0"/>
            <bin i="133" n="0"/>
            <bin i="134" n="0"/>
            <bin i="135" n="0"/>
            <bin i="136" n="0"/>
            <bin i="137" n="0"/>
            <bin i="138" n="0"/>
            <bin i="139" n="0"/>
            <bin i="140" n="0"/>
            <bin i="141" n="0"/>
            <bin i="142" n="0"/>
            <bin i="143" n="0"/>
          </left_side>
          <right_side>
            <bin i="1" n="0"/>
            <bin i="2" n="0"/>
            <bin i="3" n="0"/>
            <bin i="4" n="0"/>
            <bin i="5" n="0"/>